### ISSUE TITLE
Write hello world in Javascript

### ISSUE THREAD

**Issue by khanna98** [Code-Learn-Work/Vim-tutorial#4]

**Comment by MuhammadTanveer94** [comment]
@khanna98  i want to do this?

**Comment by khanna98** [comment]
Go Ahead 👍🏻

**Comment by MuhammadTanveer94** [comment]
@khanna98  done this below is the link to the PR:
 https://github.com/Code-Learn-Work/Vim-tutorial/pull/9

**Comment by khanna98** [comment]
#9 Resolves this issue. Now closing it.
